"""add schema integrity and audit trail

Revision ID: 562b76b61177
Revises: 089c19830e5f
Create Date: 2026-04-03 01:15:25.016298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '562b76b61177'
down_revision: Union[str, Sequence[str], None] = '089c19830e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_schema_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('old_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('old_hash', sa.Text(), nullable=True),
    sa.Column('new_hash', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'rejected', 'pending', 'auto_suspended')", name='ck_app_schema_audit_decision'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('app_registrations', sa.Column('schema_hash', sa.Text(), nullable=True))
    op.add_column('app_registrations', sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('app_registrations', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_registrations', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'app_registrations', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_registrations', type_='foreignkey')
    op.drop_column('app_registrations', 'approved_by')
    op.drop_column('app_registrations', 'approved_at')
    op.drop_column('app_registrations', 'schema_version')
    op.drop_column('app_registrations', 'schema_hash')
    op.drop_table('app_schema_audit')
    # ### end Alembic commands ###
